apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        resources:
          limits:
            memory: 200Mi
          requests:
            memory: 100Mi
        securityContext:
          privileged: true
        image: nginx:1.14.2
        ports:
        - containerPort: 80

