apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo-4
spec:
  containers:
  - name: sec-ctx-4
    image: gcr.io/google-samples/node-hello:1.0
    securityContext:
      runAsNonRoot: false
      runAsUser: 10001
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]